### ISSUE TITLE
Update political data on Foodbank and FoodbankLocation when the address changes

### ISSUE THREAD

**Issue by jasoncartwright** [givefood/givefood#184]
Fields that'll need updating when the address changes are...

- parliamentary_constituency
- parliamentary_constituency_slug
- county
- district
- ward
- mp
- mp_party
- mp_parl_id

#182

**Comment by adamalton** [comment]
Looks like a great use case for [django-dirty-fields](https://django-dirtyfields.readthedocs.io/en/develop/)!

**Comment by jasoncartwright** [comment]
Fixed in 14aea33476e105a94504fb5bf4cf1e5b8ab3cf6b
